### ISSUE TITLE
Escape string keys in shapes when needed

### ISSUE THREAD

**Issue by vudaltsov** [php-extended-type-system/type-stringifier#3]
F.e. `["'" => 1]` should be `array{'\'': 1}`. We should also check how Psalm does that.

**Comment by aivchen** [comment]
Psalm way: 
https://github.com/vimeo/psalm/blob/3af9ccde91d5eaf65741f8da0ed9cad20e5f542c/src/Psalm/Type/Atomic/TKeyedArray.php#L660-L671

Should we use the same approach?

**Comment by vudaltsov** [comment]
Yes, let's use that approach but with `var_export` instead of addslashes.
